server:
  port: 8080
  
spring:
  application:
    name: customer-orders
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING:mongodb://localhost:27017}
      database: customer-orders
      
logging:
  level:
    ROOT: ${LOG_ROOT_LEVEL:INFO}
      
api:
  paymentUrl: ${PAYMENT_URL:http://localhost:8082}
  shippingUrl: ${SHIPPING_URL:http://localhost:8083}
  customerUrl: ${CUSTOMER_URL:http://localhost:8084}
  addressUrl: ${ADDRESS_URL:http://localhost:8084}
  cardUrl: ${CARD_URL:http://localhost:8084}
  cartUrl: ${CART_URL:http://localhost:8085}
      
zone:
  ids: ${ZONE_IDS:DO:"America/Dominica",  BR:"America/Sao_Paulo", AR:"America/Buenos_Aires", EN:"America/New_York",   CO:"America/Bogota", EC:"America/Guayaquil", PE:"America/Lima", ZA:"Africa/Johannesburg", MX:"America/Mexico_City"}

threadPoolTaskExecutor:
  corePoolSize: ${CORE_POOL_SIZE:4}
  maxPoolSize: ${MAX_POOL_SIZE:10}
  queueCapacity: ${QUEUE_CAPACITY:50}

timeoutInSeconds: ${TIMEOUT_IN_SECONDS:10}

shippingAmount: ${SHIPPING_AMOUNT:10.5}